easy_admin:
    site_name: "Vigisade BO"
    user:
        name_property_path: 'firstname'
        #avatar_property_path: 'gravatar'
    design:
        brand_color: '#388ed1'
        #Menu du BO
        menu:
            - label: 'Management'
            - { entity: 'Header', label: 'Header and News', icon: 'newspaper' }
            - { entity: 'Survey', label: 'Survey', icon: 'poll-h' }
            - label: 'Direction - Area - Entity'
              icon: 'network-wired'
              children:
                  - { label: 'Direction', icon: 'network-wired', entity: 'Direction' }
                  - { label: 'Area', icon: 'project-diagram', entity: 'Area' }
                  - { label: 'Entity', icon: 'neuter', entity: 'Entity' }
            - { entity: 'TypeDangerousSituation', label: 'Types of dangerous situations', icon: 'exclamation-circle' }
            - { entity: 'BestPractice', label: 'Types of Best practice', icon: 'award'}
            - { entity: 'User', label: 'Users', icon: 'users'}

    #Action configuration
    list:
        actions:
            - { name: 'search', icon: 'search', label: 'Search' }
            - { name: 'new', icon: 'plus-circle', label: 'New' }
            - { name: 'edit', icon: 'edit', label: '' }
            - { name: 'delete', icon: 'trash', label: '' }
            - { name: 'show', icon: 'eye', label: '' }

    #Entities configuration
    entities:
        #Management Header & News
        Header:
            class: App\Entity\Header
            disabled_actions: ['new', 'search', 'delete']
            form: # 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'logoText', label: 'Text' }
                    - { property: 'news', type: 'fos_ckeditor' }
                    - { property: 'logoImage', label: 'Logo', type: 'vich_image', type_options: { allow_delete: false} }
            list:
                title: 'List of header'
                fields:
                    - { property: 'logoText', label: 'Text' }
                    - { property: 'news'}
                    - { property: 'image', type: 'image', base_path: '%app.path.header_images%' }
            show:
                fields:
                    - { property: 'logoText', label: 'Text' }
                    - { property: 'news'}
                    - { property: 'image', type: 'image', base_path: '%app.path.header_images%' }

        #Management Direction
        Direction:
            class: App\Entity\Direction
            list:
                title: 'List of directions'
                fields:
                    - { property: 'id', label: 'ID' }
                    - { property: 'name', label: 'Name' }
            form: # 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'name', label: 'Name' }

        #Management Area
        Area:
            class: App\Entity\Area
            list:
                title: 'List of areas'
                fields:
                    - { property: 'id', label: 'ID' }
                    - { property: 'name', label: 'Name' }
                    - { property: 'direction', label: 'Direction' }
            form: # 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'name', label: 'Name' }
                    - { property: 'direction', label: 'Direction' }
        #Management Entity
        Entity:
            class: App\Entity\Entity
            list:
                title: 'List of entities'
            form: # 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'name', label: 'Name' }
                    - { property: 'area', label: 'Area' }

        #Management User
        User:
            class: App\Entity\User
            controller: App\Controller\UserController
            password_encoding: { algorithm: 'auto' }
            disabled_actions: ['show']
            form: # 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { type: 'group', columns: 5, label: 'User Details', icon: 'user' }
                    - { property: 'email', type: 'email' }
                    - { property: 'password', type: 'password', help: 'Passwords must have at least 8 characters'}
                    - { property: 'firstname' }
                    - { property: 'lastname' }
                    - { property: 'imageFile', type: 'vich_image', css_class: '' }
                    - { type: 'group', columns: 7, label: 'Direction - Area - Entity', icon: 'network-wired' }
                    - { property: 'direction' }
                    - { property: 'area' }
                    - { property: 'entity' }
                    - { type: 'section', label: 'Role & status', icon: 'minus-square',
                        help: 'Role is preferred'}
                    - { property: 'roles', type: 'choice', type_options: {
                        multiple: true,
                        expanded: false,
                        mapped: true,
                        choices: {
                            'ROLE_CONDUCTEUR': 'ROLE_CONDUCTEUR',
                            'ROLE_MANAGER': 'ROLE_MANAGER',
                            'ROLE_ADMIN': 'ROLE_ADMIN'
                        }}}
                    - { property: 'actif'}
            list:
                fields:
                    - { property: 'email' }
                    - { property: 'firstname' }
                    - { property: 'lastname' }
                    - { property: 'image', type: 'image', base_path: '%app.path.user_images%' }
                    - { property: 'actif' }
                    - { property: 'direction' }
                    - { property: 'area' }
                    - { property: 'entity' }
                    - { property: 'roles'}

        #Management Survey
        Survey:
            class: App\Entity\Survey
            form: # 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'translations', label: false, type: A2lix\TranslationFormBundle\Form\Type\TranslationsType, type_options: { required: true} }
                    - { property: 'team', type: 'choice', type_options: {
                        multiple: false,
                        expanded: false,
                        mapped: true,
                        choices: {
                            'Equipe': 'Equipe',
                            'Responsable': 'Responsable',
                            'Aucun': 'Aucun'
                        }}}
                    - { property: 'direction' }
                    - property: 'categories'
                      label: 'Rubrique'
                      type: 'collection'
                      type_options:
                          entry_type: App\Form\SurveyCategoryEmbeddedForm
                          allow_delete: true
                          allow_add: true
                          by_reference: false
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'direction' }
                    - { property: 'team' }
                    - { property: 'categories' }
            show:
                fields:
                    - { property: 'title' }
                    - { property: 'direction' }
                    - { property: 'categories' }

        #Management Best practice
        BestPractice:
            class: App\Entity\BestPractice
            label: 'Best Practice'
            list:
                fields:
                  - { property: 'id'}
                  - { property: 'type' }
            form:
                fields:
                    - { property: 'translations', label: false, type: A2lix\TranslationFormBundle\Form\Type\TranslationsType, type_options: { required: true} }

        #Management Dangerous Situation
        TypeDangerousSituation:
            class: App\Entity\TypeDangerousSituation
            label: 'List of Type Dangerous Situation'
            list:
                fields:
                    - { property: 'id'}
                    - { property: 'type' }
            form:
                fields:
                    - { property: 'translations', label: false, type: A2lix\TranslationFormBundle\Form\Type\TranslationsType, type_options: { required: true} }
