easy_admin:
    site_name: "Vigisade BO"
    user:
        name_property_path: 'firstname'
        #avatar_property_path: 'gravatar'
    design:
        brand_color: '#388ed1'
        #Menu du BO
        menu:
            - label: 'GÉNÉRAL'
            - { entity: 'Header', label: 'Gérer les actualités', icon: 'newspaper' }
            - { entity: 'Survey', label: 'Gérer les questionnaires', icon: 'poll-h' }
            - label: 'Gérer les directions, les zones et les entités'
              icon: 'network-wired'
              children:
                  - { label: 'Direction', icon: 'network-wired', entity: 'Direction' }
                  - { label: 'Zone', icon: 'project-diagram', entity: 'Area' }
                  - { label: 'Entité', icon: 'neuter', entity: 'Entity' }
            - { entity: 'User', label: 'Gérer les utilisateurs', icon: 'users'}
            - label: 'PARAMÈTRES'
            - { entity: 'TypeDangerousSituation', label: 'Gérer les types de situations dangereuses', icon: 'exclamation-circle' }
            - { entity: 'BestPractice', label: 'Gérer les types de bonnes pratiques', icon: 'award'}


    #Action configuration
    list:
        actions:
            - { name: 'search', icon: 'search', label: 'Recherche' }
            - { name: 'new', icon: 'plus-circle', label: 'Nouveau' }
            - { name: 'edit', icon: 'edit', label: '' }
            - { name: 'delete', icon: 'trash', label: '' }
            - { name: 'show', icon: 'eye', label: '' }

    #Entities configuration
    entities:
        #Management Header & News
        Header:
            class: App\Entity\Header
            disabled_actions: ['new', 'search', 'delete', 'show']
            form: # 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'logoText', label: 'Titre' }
                    - { property: 'news', type: 'fos_ckeditor', label: 'Actualités' }
            list:
                title: 'Actualités'
                fields:
                    - { property: 'logoText', label: 'Titre' }
                    - { property: 'news', label: 'Actualités' }

        #Management Direction
        Direction:
            class: App\Entity\Direction
            controller: App\Controller\Admin\DirectionController
            disabled_actions: ['delete', 'show']
            list:
                title: 'Directions'
                fields:
                    - { property: 'id', label: 'ID' }
                    - { property: 'name', label: 'Direction' }
                    - { property: 'etat', label: 'Statut' }
            form: # 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'name', label: 'Nom Direction' }
                    - { property: 'etat', label: 'Actif' }

        #Management Area
        Area:
            class: App\Entity\Area
            controller: App\Controller\Admin\AreaController
            label : 'Zone'
            disabled_actions: ['delete', 'show']
            list:
                title: '%%entity_label%%s'
                fields:
                    - { property: 'id', label: 'ID' }
                    - { property: 'name', label: '%%entity_label%%' }
                    - { property: 'direction', label: 'Direction' }
                    - { property: 'etat', label: 'Statut' }
            form: # 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'name', label: 'Nom Zone' }
                    - { property: 'direction', label: 'Direction', type_options: { required: true} }
                    - { property: 'etat', label: 'Actif' }
            search:
                help: null
                fields: ['id', 'name', 'direction.name', 'etat']
            edit:
                title: 'Modifier %%entity_label%%'
            new:
                title: 'Créer %%entity_label%%'

        #Management Entity
        Entity:
            class: App\Entity\Entity
            controller: App\Controller\Admin\EntityController
            label: 'Entité'
            disabled_actions: ['delete', 'show']
            list:
                title: '%%entity_label%%s'
                fields:
                    - { property: 'id', label: 'ID' }
                    - { property: 'name', label: '%%entity_label%%' }
                    - { property: 'area', label: 'Zone' }
                    - { property: 'etat', label: 'Etat' }
            form: # 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'name', label: 'Nom Entité' }
                    - { property: 'area', label: 'Zone', type_options: { required: true} }
                    - { property: 'etat', label: 'Actif' }
            search:
                help: null
                fields: ['id', 'name', 'area.name']
            edit:
                title: 'Modifier %%entity_label%%'
            new:
                title: 'Créer %%entity_label%%'


        #Management User
        User:
            class: App\Entity\User
            controller: App\Controller\Admin\UserController
            label: 'Utilisateurs'
            password_encoding: { algorithm: 'auto' }
            disabled_actions: ['show', 'delete']
            edit: # 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { type: 'group', columns: 5, label: 'Informations utilisateur', icon: 'user' }
                    - { property: 'email', type: 'email' }
                    - { property: 'plainPassword', label: 'Mot de passe', type: 'password', help: 'Le mot de passe doit contenir au moins 8 caractères'}
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'imageFile', label: 'Image Utilisateur', type: 'vich_image', css_class: '' }
                    - { type: 'group', columns: 7, label: 'Direction - Zone - Entité', icon: 'network-wired' }
                    - { property: 'direction', label: 'Direction' }
                    - { property: 'area', label: 'Zone' }
                    - { property: 'entity', label: 'Entité' }
                    - { type: 'section', label: 'Rôles et Statut', icon: 'minus-square',
                        help: 'Sélectionnez au moins un rôle'}
                    - { property: 'roles', label: 'Rôles', type: 'choice', type_options: {
                        multiple: true,
                        expanded: false,
                        mapped: true,
                        choices: {
                            'ROLE_CONDUCTEUR': 'ROLE_CONDUCTEUR',
                            'ROLE_MANAGER': 'ROLE_MANAGER',
                            'ROLE_ADMIN': 'ROLE_ADMIN'
                        }}}
                    - { property: 'actif', label: 'Actif'}
            new: # 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { type: 'group', columns: 5, label: 'Informations utilisateur', icon: 'user' }
                    - { property: 'email', type: 'email' }
                    - { property: 'plainPassword', label: 'Mot de passe', type: 'password', help: 'Le mot de passe doit contenir au moins 8 caractères', type_options: { required: true}}
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image', css_class: '' }
                    - { type: 'group', columns: 7, label: 'Direction - Zone - Entité', icon: 'network-wired' }
                    - { property: 'direction', label: 'Direction' }
                    - { property: 'area', label: 'Zone' }
                    - { property: 'entity', label: 'Entité' }
                    - { type: 'section', label: 'Rôles et Statut', icon: 'minus-square',
                        help: 'Sélectionnez au moins un rôle'}
                    - { property: 'roles', label: 'Rôles', type: 'choice', type_options: {
                        multiple: true,
                        expanded: false,
                        mapped: true,
                        choices: {
                            'ROLE_CONDUCTEUR': 'ROLE_CONDUCTEUR',
                            'ROLE_MANAGER': 'ROLE_MANAGER',
                            'ROLE_ADMIN': 'ROLE_ADMIN'
                        }}}
                    - { property: 'actif', label: 'Actif'}
            list:
                fields:
                    - { property: 'email', label: 'Email' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'actif', label: 'Statut' }
                    - { property: 'direction', label: 'Direction' }
                    - { property: 'area', label: 'Zone' }
                    - { property: 'entity', label: 'Entité' }
                    - { property: 'roles', label: 'Rôles', template: bundles/EasyAdminBundle/_list_field_user_role.html.twig}
            search:
                help: null
                fields: ['email', 'firstname', 'lastname', 'actif', 'direction.name', 'area.name', 'roles']

        #Management SurveyQuestion
        SurveyQuestion:
            class: App\Entity\SurveyQuestion
            label: 'Formulaire de question'
            controller: App\Controller\Admin\SurveyQuestionController
            disabled_actions: ['show', 'list', 'delete']
            form: # 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'questionType', type: choice, type_options: {choices: {'Equipe':'Equipe', 'General':'General'}} }
                    - { property: 'translations', label: 'Langues', type: A2lix\TranslationFormBundle\Form\Type\TranslationsType, type_options: { required: true} }

        #Management SurveyCategory
        SurveyCategory:
            class: App\Entity\SurveyCategory
            label: 'Formulaire de rubrique'
            disabled_actions: ['show', 'list', 'delete']
            controller: App\Controller\Admin\SurveyCategoryController
            templates:
              edit: 'admin/surveyCategory/edit.html.twig'
            form: # 'form' is applied to both 'new' and 'edit' views
                fields:
                - { property: 'translations', label: 'Langues', type: A2lix\TranslationFormBundle\Form\Type\TranslationsType, type_options: { required: true} }
            list:
                fields:
                - { property: 'id' }
        Survey:
            class: App\Entity\Survey
            label: 'Formulaire de visite'
            disabled_actions: ['delete', 'show']
            controller: App\Controller\Admin\SurveyController
            templates:
                edit: 'admin/survey/edit.html.twig'
            form: # 'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'translations', label: 'Langues', type: A2lix\TranslationFormBundle\Form\Type\TranslationsType, type_options: { required: true} }
                    - { property: 'team', label: 'Equipe Contrôlé', type: 'choice', type_options: {
                        multiple: false,
                        expanded: false,
                        mapped: true,
                        choices: {
                            'Aucun': 'Aucun',
                            'Equipe': 'Equipe',
                            'Responsable': 'Responsable'
                        }}}
                    - { property: 'direction' }
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'title', label: 'Titre du Formulaire' }
                    - { property: 'direction', label: 'Direction(s)' }
                    - { property: 'categories', label: 'Nombre de rubriques' }
            search:
                help: null
                fields: ['translations.title', 'direction.name']

        #Management Best practice
        BestPractice:
            class: App\Entity\BestPractice
            disabled_actions: ['delete', 'search','show']
            label: 'Types de bonnes pratiques'
            list:
                fields:
                  - { property: 'id'}
                  - { property: 'type', label: 'Type' }
                  - { property: 'status', label: 'Statut' }
            form:
                fields:
                    - { property: 'translations', label: 'Langues', type: A2lix\TranslationFormBundle\Form\Type\TranslationsType, type_options: { required: true} }
                    - { property: 'status', label: 'Actif' }

        #Management Dangerous Situation
        TypeDangerousSituation:
            class: App\Entity\TypeDangerousSituation
            disabled_actions: ['delete', 'search','show']
            label: 'Types de situations dangereuses'
            list:
                fields:
                    - { property: 'id'}
                    - { property: 'type', label: 'Type' }
                    - { property: 'status', label: 'Statut' }
            form:
                fields:
                    - { property: 'translations', label: 'Langues', type: A2lix\TranslationFormBundle\Form\Type\TranslationsType, type_options: { required: true} }
                    - { property: 'status', label: 'Actif' }
