vich_uploader:
    db_driver: orm

    mappings:
        header_images:
            # uri prefix to resource
            uri_prefix: '%app.path.header_images%'
            # gaufrette storage fs id, required
            upload_destination: '%kernel.project_dir%/public%app.path.header_images%'
            delete_on_remove :    true  # determine whether to delete file upon removal of entity
            delete_on_update :    true  # determine wheter to delete the file upon update of entity
