api.corrective_action.get:
  path: /
  controller: App\Controller\Api\CorrectiveActionController::getCorrectiveActions
  methods: GET

api.corrective_action.update:
  path: /update/
  controller: App\Controller\Api\CorrectiveActionController::updateCorrectiveAction
  methods: POST
