api.survey.get:
  path: /
  controller: App\Controller\Api\SurveyController::getSurvey
  methods: GET

api.survey.create:
  path: /create/
  controller: App\Controller\Api\SurveyController::createResult
  methods: POST

api.survey.update:
  path: /update/
  controller: App\Controller\Api\SurveyController::updateResult
  methods: POST

api.survey.history:
  path: /history/
  controller: App\Controller\Api\SurveyController::getResults
  methods: GET

api.survey.item:
  path: /history/{id}/
  controller: App\Controller\Api\SurveyController::getResult
  methods: GET
