api.user:
  resource: api/user.yaml
  prefix: /user

api.survey:
  resource: api/survey.yaml
  prefix: /survey

api.result:
  resource: api/result.yaml
  prefix: /survey

api.corrective_action:
  resource: api/corrective_action.yaml
  prefix: /corrective-action

api.dangerous_situation:
  resource: api/dangerous_situation.yaml
  prefix: /dangerous-situation

api.settings:
  path: /settings/
  controller: App\Controller\Api\SettingsController::getSettings
  methods: GET

api.header:
  resource: api/header.yaml
  prefix: /header

api.direction_zone_entity_type_dangerous_situation:
  path: /direction-zone-entity-type-dangerous-situation
  controller: App\Controller\Api\DirectionZoneEntityController::getDirectionZoneEntityTypeDangerousSituation
  methods: GET
