#!/usr/bin/env bash

set -e

OPTIONS=
for p in "$@"; do
    if [ "$p" = "-T" -o "$p" = "-I" ]; then
        OPTIONS="$OPTIONS $p"
        shift
    else
        break
    fi
done

if [ -f "/.dockerenv" ]; then
    exec /usr/local/bin/composer "$@"
fi

exec $(dirname $0)/../../.docker/exec $OPTIONS php composer "$@"

# vim: ts=4 sts=4 sw=4 et:
