#!/usr/bin/env bash

SERVICE=php
BIN_PHP_COMMAND=${BIN_PHP_COMMAND:-php}

set -e

OPTIONS=
for p in "$@"; do
    if [ "$p" = "-T" -o "$p" = "-I" ]; then
        OPTIONS="$OPTIONS $p"
        shift
    else
        break
    fi
done

if [ -f "/.dockerenv" ]; then
    exec "$BIN_PHP_COMMAND" "$@"
fi

exec $(dirname $0)/../../.docker/exec.sh $OPTIONS "$SERVICE" "$BIN_PHP_COMMAND" "$@"

# vim: ts=4 sts=4 sw=4 et:
