# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

api:
  resource: routes/api.yaml
  prefix: /api

api_login_check:
  path: /api/login_check

admin:
  resource: routes/admin.yaml
  prefix: /admin

ajax_request_area:
  path: /ajax_request_area
  controller: App\Controller\Back\AsyncController::getSpecificAreaSelect

ajax_request_entity:
  path: /ajax_request_entity
  controller: App\Controller\Back\AsyncController::getSpecificEntitySelect
